zeebe:
  client:
    broker:
      gateway-address: ${ZEEBE_CLIENT_BROKER_GATEWAY_ADDRESS:127.0.0.1:26500}
    security:
      plaintext: ${ZEEBE_CLIENT_SECURITY_PLAINTEXT:true}
    cloud:
      cluster-id: ${ZEEBE_CLIENT_CLOUD_CLUSTER_ID}
      client-id: ${ZEEBE_CLIENT_CLOUD_CLIENT_ID}
      client-secret: ${ZEEBE_CLIENT_CLOUD_CLIENT_SECRET}
      region: ${ZEEBE_CLIENT_CLOUD_REGION}

spring:
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: 6379

logging:
  level:
    io.camunda.zeebe: INFO

server:
  port: 8080
