zeebe:
  client:
    broker:
      gateway-address: ${ZEEBE_CLIENT_BROKER_GATEWAY-ADDRESS:127.0.0.1:26500}
    security:
      plaintext: true # Set to false for SaaS

spring:
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: 6379

logging:
  level:
    io.camunda.zeebe: INFO

server:
  port: 8080
