zeebe:
  client:
    broker:
      gateway-address: ${ZEEBE_CLIENT_BROKER_GATEWAY-ADDRESS:127.0.0.1:26500}
    security:
      plaintext: ${ZEEBE_CLIENT_SECURITY_PLAINTEXT:true}

logging:
  level:
    io.camunda.zeebe: INFO

server:
  port: 8080
